# Site settings
title: Amy Paguirigan
baseurl: ""
url: "https://vortexcing.github.io"
google_analytics: G-91W4G2FCSB  # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Amy Paguirigan
  desc: Cancer Research Scientist.  Coddiwompling through Life. 
  email: amy.tldr@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: vortexing
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/amy-paguirigan-75a7299/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/projects/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
