
title: Amy Paguirigan, PhD
subtitle: 
logo: 
repository: "vortexing/vortexing.github.io"
email: amy.tldr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An overview of the research, projects and professional expertise for Amy Paguirigan, PhD.
twitter_username: amy_paguirigan
github_username: vortexing
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Los_Angeles"
locale: "en-US"
include:
  - _pages
atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Amy Paguirigan"
  avatar : "/assets/images/amy-bwback.jpg"
  bio    : "Scientific non-conformist working in translational genomics and research information technology."
  links:
    - label: "Seattle, WA"
      icon: "fa fa-solid fa-map-pin"
      url: ""
    - label: "Email"
      icon: "fa fa-solid fa-envelope"
      url: "mailto:amy.tldr@gmail.com"
    - label: "GitHub"
      icon: "fab fa-brands fa-github"
      url: "https://github.com/vortexing"
    - label: "LinkedIn"
      icon: "fab fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/amy-paguirigan-75a7299/"
    - label: "Google Scholar"
      icon: "fab fa-brands fa-google"
      url: "https://scholar.google.com/citations?hl=en&user=NroSeOUAAAAJ"
    - label: "Twitter"
      icon: "fab fa-brands fa-twitter-square"
      url: "https://twitter.com/amy_paguirigan"

footer:
  links:
    - label: "Email"
      icon: "fa fa-solid fa-envelope"
      url: "mailto:amy.tldr@gmail.com"
    - label: "GitHub"
      icon: "fab fa-brands fa-github"
      url: "https://github.com/vortexing"
    - label: "LinkedIn"
      icon: "fab fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/amy-paguirigan-75a7299/"
    - label: "Google Scholar"
      icon: "fab fa-brands fa-google"
      url: "https://scholar.google.com/citations?hl=en&user=NroSeOUAAAAJ"
    - label: "Twitter"
      icon: "fab fa-brands fa-twitter-square"
      url: "https://twitter.com/amy_paguirigan"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true
      toc_label: "Quick Look"
      toc_sticky: true


